name: Automacao WalkDog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: browser-actions/setup-chrome@v1
        with:
         chrome-version: 120
         install-chromedriver: true

      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build com Maven
        run: mvn -B clean package --file pom.xml

      - name: Executar testes
        run: mvn test