name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # ou a versão do Java que você estiver usando

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests with Maven
        run: mvn test
        env:
          # Variável de ambiente necessária para execução
          DISPLAY: ':99.0'

    # Você pode adicionar aqui mais etapas como relatório ou upload de artefatos, se necessário.
